authors:
  girishgovilkar:
    name: Girish Govilkar
    description: Data & AI Engineer & Founder of SkillEase
    avatar: https://avatars.githubusercontent.com/u/34709402?s=400&u=93706427f5441fa0d10086a0bc1b6298b06534df&v=4
    url: https://www.linkedin.com/in/girishgovilkar/